"""add date and time

Revision ID: 520f35e62674
Revises: 8f01ee490ca7
Create Date: 2018-04-26 16:33:06.221101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '520f35e62674'
down_revision = '8f01ee490ca7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('date', sa.String(), nullable=True))
    op.add_column('events', sa.Column('time', sa.String(), nullable=True))
    op.drop_column('events', 'd')
    op.drop_column('events', 'y')
    op.drop_column('events', 'm')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('m', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('y', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('d', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('events', 'time')
    op.drop_column('events', 'date')
    # ### end Alembic commands ###
