"""y/m/d added to events table

Revision ID: 8f01ee490ca7
Revises: f4a8d534104e
Create Date: 2018-04-25 15:26:01.221786

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8f01ee490ca7'
down_revision = 'f4a8d534104e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('d', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('m', sa.Integer(), nullable=True))
    op.add_column('events', sa.Column('y', sa.Integer(), nullable=True))
    op.drop_column('events', 'when')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('when', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('events', 'y')
    op.drop_column('events', 'm')
    op.drop_column('events', 'd')
    # ### end Alembic commands ###
