"""contact columns added to events table

Revision ID: f4a8d534104e
Revises: b55433034120
Create Date: 2018-04-25 14:45:55.669267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4a8d534104e'
down_revision = 'b55433034120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('events', sa.Column('phone', sa.String(length=255), nullable=True))
    op.drop_constraint('events_contacts_id_fkey', 'events', type_='foreignkey')
    op.drop_column('events', 'contacts_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('contacts_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('events_contacts_id_fkey', 'events', 'contacts', ['contacts_id'], ['id'])
    op.drop_column('events', 'phone')
    op.drop_column('events', 'name')
    # ### end Alembic commands ###
